[filter]

[filter.myfilter]
type = "USER"
list = ["mani123#7703"]
filter-actions = ["sendErrorMuteEmbed"]

# Configure command interactions
[[command]]
actionsIds = ["mutecmd"]
filtersIds = ["myfilter"]
name = "mute"
description = "mute selected user"
optionIds = ["users1"]

[command.option]

[command.option.users1]
name = "listofusers"
description = "List of users"
type = "user"
required = true

[[command]]
actionsIds = ["unmutecmd"]
filtersIds = ["myfilter"]
name = "unmute"
description = "unmute selected user"
optionIds = ["users"]

[command.option]

[command.option.users]
name = "listofusers"
description = "List of users"
type = "user"
required = true

