[filter]

[filter.myfilter]
type = "USER"
before-filter-actions = ["addAdminUsers"]
filter-actions = ["sendErrorMuteEmbed"]

# Configure command interactions
[[interaction]]
type = "command"
actionsIds = ["mutecmd"]
filtersIds = ["myfilter"]
name = "mute"
description = "mute selected user"
optionIds = ["users1"]

[interaction.option]

[interaction.option.users1]
name = "listofusers"
description = "List of users"
type = "user"
required = true

[[interaction]]
type = "command"
actionsIds = ["unmutecmd"]
filtersIds = ["myfilter"]
name = "unmute"
description = "unmute selected user"
optionIds = ["users"]

[interaction.option]

[interaction.option.users]
name = "listofusers"
description = "List of users"
type = "user"
required = true

