# Files starting with '_' will not be loaded
[[action]]
type = "TEMP_DATA_ADD"
focusedUserOptionIds = ["listofusers"]
[[action]]
type = "MUTE_USER"
[[action]]
type = "DEAFEN_USER"
[[action]]
type = "SEND_EMBED"
title = "Success"
description = "You success unmuted user"
ephemeral = true