[[action]]
type = "TEMP_DATA_ADD"
focusedUserOptionIds = ["listofusers"]
[[action]]
type = "UNMUTE_USER"
[[action]]
type = "UNDEAFEN_USER"
[[action]]
type = "SEND_EMBED"
title = "Success"
description = "You success unmuted user"
ephemeral = true